# Generated by Django 4.0.4 on 2022-04-17 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('course', models.IntegerField()),
                ('group', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NIRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_finish', models.DateField(blank=True, null=True, verbose_name='Complete')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('place', models.CharField(default='СТИ НИЯУ "МИФИ"', max_length=200)),
                ('date_of_the_event', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='student.student')),
                ('supervisors', models.ManyToManyField(to='student.supervisor')),
            ],
            options={
                'ordering': ['date_of_the_event'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ID', models.IntegerField(blank=True, null=True)),
                ('date_of_publication', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='student.student')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.supervisor')),
            ],
            options={
                'ordering': ['date_of_publication'],
            },
        ),
    ]
