# Generated by Django 4.0.4 on 2022-04-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ID',
            field=models.CharField(max_length=50),
        ),
    ]
