# Generated by Django 4.0.4 on 2022-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nirs',
            name='author',
        ),
        migrations.AddField(
            model_name='nirs',
            name='authors',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
