# Generated by Django 4.0.4 on 2022-04-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_document_description_alter_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nirs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.nirs'),
        ),
    ]
