# Generated by Django 4.0.4 on 2022-04-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nirs',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'plan'), ('2', 'work'), ('3', 'finish')], default='1', max_length=1),
        ),
    ]
